# Generated by Django 3.2.3 on 2021-05-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0008_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
    ]
