# Generated by Django 3.2.3 on 2021-05-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0009_remove_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='DEFAULT VALUE', max_length=1000),
        ),
    ]
