# Generated by Django 3.2.3 on 2021-05-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0012_auto_20210526_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='_pixels_image_likes_+', to='pixels.Like'),
        ),
    ]
