# Generated by Django 3.2.3 on 2021-05-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0015_auto_20210526_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
    ]
